name: CI/CD for Angular and Docusaurus Apps

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: write # Needed for GitHub Pages deployment
  pages: write # Docusaurus requires this for GitHub Pages
  id-token: write # Docusaurus uses this for secure deployments

env:
  # Optimize memory usage for Node.js
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  deploy-angular:
    runs-on: ubuntu-latest
    name: Build and Deploy Angular App
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: LintApp
        run: npx nx affected --target=lint --base=origin/main --head=HEAD

      - name: Test App
        run: npx nx affected --target=test --base=origin/main --head=HEAD

      - name: Build main app
        run: npx nx run basitjamil:build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload app Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/apps/basitjamil/' # The Docusaurus build directory

      - name: Deploy app to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
